version: '3.3'
services:
  #----------  HTML Services  -------
  freelancenow:
    build: ./
    container_name: freelancenow
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - EXPRESSPORT=
      - EXPRESS_SESSION_SECRET=
      - BID=
      - paypalUser=
      - paypalPass=
    networks:
      - nginx_network

  #-----------      DATABASE     ----------
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - "./db:/data/db"
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
