version: '3.3'
services:
  #----------  HTML/Fetch Services  -------
  freelancenow:
    build: ./
    container_name: freelancenow
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - EXPRESSPORT=8080

  #-----------      DATABASE     ----------
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - "${GITLABRUNNERDB}/mongodbfreelance:/data/db"
