name: Linter Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: pwd && ls
    - name: Install npm dependencies
      run: npm install
    - name: Run linter
      run: npm run linter
