name: Linter Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Navigate to dir
      run: cd freelance-now
    - name: Install npm dependencies
      run: npm install
    - name: Run linter
      run: npm run linter
