name: Linter Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Install npm dependencies
      run: cd freelance-now && npm install
    - name: Run linter
      run: cd freelance-now && npm run linter
